// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN9fXGvWdQfam5rzuP63J_7qJfSMV-FCg',
    appId: '1:869905958615:web:aa6027ff431f4b7ca0d292',
    messagingSenderId: '869905958615',
    projectId: 'ghost-app-61105',
    authDomain: 'ghost-app-61105.firebaseapp.com',
    storageBucket: 'ghost-app-61105.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGsugZM9koD4gC0X5mfQTsXCTqkegigfg',
    appId: '1:869905958615:android:fc3974681c23534fa0d292',
    messagingSenderId: '869905958615',
    projectId: 'ghost-app-61105',
    storageBucket: 'ghost-app-61105.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwqYKHNmGSjseffrUx-Tv57hlC3HfaOgw',
    appId: '1:869905958615:ios:79f19cade94230c9a0d292',
    messagingSenderId: '869905958615',
    projectId: 'ghost-app-61105',
    storageBucket: 'ghost-app-61105.firebasestorage.app',
    iosBundleId: 'com.example.ghostApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwqYKHNmGSjseffrUx-Tv57hlC3HfaOgw',
    appId: '1:869905958615:ios:79f19cade94230c9a0d292',
    messagingSenderId: '869905958615',
    projectId: 'ghost-app-61105',
    storageBucket: 'ghost-app-61105.firebasestorage.app',
    iosBundleId: 'com.example.ghostApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN9fXGvWdQfam5rzuP63J_7qJfSMV-FCg',
    appId: '1:869905958615:web:8094bc45564d7308a0d292',
    messagingSenderId: '869905958615',
    projectId: 'ghost-app-61105',
    authDomain: 'ghost-app-61105.firebaseapp.com',
    storageBucket: 'ghost-app-61105.firebasestorage.app',
  );
}
